apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoomcamp-model
spec:
  selector:
    matchLabels:
      app: zoomcamp-model
  replicas: 1
  template:
    metadata:
      labels:
        app: zoomcamp-model
    spec:
      containers:
      - name: zoomcamp-model
        image: zoomcamp-model:3.13.10-hw10
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"            
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 9696
