[project]
name = "midterm-project"
version = "0.1.0"
description = "Score Prediction Project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.2",
    "scikit-learn>=1.7.2",
    "unicorn>=2.1.4",
    "xgboost>=3.1.1",
]
